name: Auto Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          OAUTH_GOOGLE_CLIENT_ID: dummy
          OAUTH_GOOGLE_CLIENT_SECRET: dummy

          OAUTH_NAVER_CLIENT_ID: dummy
          OAUTH_NAVER_CLIENT_SECRET: dummy

          OAUTH_KAKAO_CLIENT_ID: dummy
          OAUTH_KAKAO_CLIENT_SECRET: dummy

          SLACK_ERROR_WEBHOOK: dummy
        run: ./gradlew clean build -x test -Dspring.profiles.active=prod

      - name: Rename jar to app.jar
        run: |
          JAR_FILE=$(ls build/libs/*.jar | grep -v plain | head -n 1)
          cp "$JAR_FILE" build/libs/app.jar

      - name: Transfer app.jar to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "build/libs/app.jar"
          target: ${{ secrets.WORK_DIR }}
          rm: false

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Restarting konect service..."
            sudo systemctl restart konect
            echo "Checking service status..."
            sudo systemctl status konect --no-pager
            echo "Deployment completed"
